title: Pedro Reis
tagline: "Computer Science, Data Analysis, Software Engineering"
description: "engineer / photographer / scientist"
baseurl: ""
url: ""
email: pedromreis@gmail.com
twitter_username: pedrombreis
github_username:  pmreis
linkedin_link: http://www.linkedin.com/in/pmreis

markdown: kramdown
permalink: pretty
#excerpt_separator: <!--more-->

kramdown:
  # use_coderay: false
  input: GFM

#lsi: true

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/p:num"


